# 01 - Data Collection

## Purpose

This notebook imports the raw Eurovision datasets into the project, performs
basic validation, filters the competition years used in the study, and stores
the cleaned raw datasets for use in subsequent notebooks.

This notebook does not perform feature engineering or model preparation.

In [4]:
# Mount Google Drive

from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
# Import project configuration

import sys

sys.path.append("/content/drive/MyDrive/Eurovision_Prediction")

from config import *

In [6]:
import pandas as pd
import shutil
from pathlib import Path

In [8]:
print(PROJECT_ROOT)
print(RAW_DATA)
print(PROCESSED_DATA)

/content/drive/MyDrive/Eurovision_Prediction
/content/drive/MyDrive/Eurovision_Prediction/data/raw
/content/drive/MyDrive/Eurovision_Prediction/data/processed

In [9]:
DATASETS = PROJECT_ROOT / "datasets"

contestants_path = DATASETS / "contestants.csv"
votes_path = DATASETS / "votes.csv"

In [10]:
contestants = pd.read_csv(contestants_path)
votes = pd.read_csv(votes_path)

print("Contestants:", contestants.shape)
print("Votes:", votes.shape)

Contestants: (2501, 21)
Votes: (56562, 9)

In [11]:
display(contestants.head())

display(votes.head())

,year,to_country_id,to_country,performer,song,place_contest,sf_num,running_final,running_sf,place_final,...,place_sf,points_sf,points_tele_final,points_jury_final,points_tele_sf,points_jury_sf,composers,lyricists,lyrics,youtube_url
0,1956,ch,Switzerland,Refrain,Lys Assia,1.0,NaN,9.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,Géo Voumard,Émile Gardaz,"Refrain\n\n(Refrain d'amour…)\n\nRefrain, coul...",https://youtube.com/watch?v=9POvOONqAj0
1,1956,nl,Netherlands,Holland,De Vogels Van Jetty Paerl,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Cor Lemaire,Annie M. G. Schmidt,De vogels van Holland\n\nDe vogels van Holland...,https://youtube.com/watch?v=73FpzjAV15w
2,1956,ch,Switzerland,Lys Assia,Das Alte Karussell,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,George Betz-Stahl,NaN,Das alte Karussell\n\nDas alte Karussell\nDas ...,https://youtube.com/watch?v=lVpf8uzHnX0
3,1956,be,Belgium,Fud Leclerc,Messieurs Les Noyés De La Seine,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Jack Say;Jean Miret,Robert Montal,Messieurs les noyés de la Seine\n\nMessieurs l...,https://youtube.com/watch?v=U9O3sqlyra0
4,1956,de,Germany,Walter Andreas Schwarz,Im Wartesaal Zum Großen Glück,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Walter Andreas Schwarz,NaN,Im Wartesaal zum großen Glück\n\nEs gibt einen...,https://youtube.com/watch?v=jqo-whfb0mk

,year,round,from_country_id,to_country_id,from_country,to_country,total_points,tele_points,jury_points
0,1957,final,at,nl,at,nl,6,NaN,NaN
1,1957,final,at,fr,at,fr,0,NaN,NaN
2,1957,final,at,dk,at,dk,0,NaN,NaN
3,1957,final,at,lu,at,lu,3,NaN,NaN
4,1957,final,at,de,at,de,0,NaN,NaN

In [12]:
contestants.info()

print()

votes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2501 entries, 0 to 2500
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               2501 non-null   int64
 1   to_country_id      2501 non-null   object
 2   to_country         2501 non-null   object
 3   performer          2501 non-null   object
 4   song               2499 non-null   object
 5   place_contest      1775 non-null   float64
 6   sf_num             713 non-null    float64
 7   running_final      1474 non-null   float64
 8   running_sf         713 non-null    float64
 9   place_final        1462 non-null   float64
 10  points_final       1461 non-null   float64
 11  place_sf           713 non-null    float64
 12  points_sf          713 non-null    float64
 13  points_tele_final  257 non-null    float64
 14  points_jury_final  257 non-null    float64
 15  points_tele_sf     242 non-null    float64
 16  points_jury_sf     242 non-null    float64
 17  composers          2501 non-null   object
 18  lyricists          1433 non-null   object
 19  lyrics             2501 non-null   object
 20  youtube_url        2501 non-null   object
dtypes: float64(12), int64(1), object(8)
memory usage: 410.4+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56562 entries, 0 to 56561
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             56562 non-null  int64
 1   round            56562 non-null  object
 2   from_country_id  56562 non-null  object
 3   to_country_id    56562 non-null  object
 4   from_country     56562 non-null  object
 5   to_country       56562 non-null  object
 6   total_points     56562 non-null  int64
 7   tele_points      16949 non-null  float64
 8   jury_points      16949 non-null  float64
dtypes: float64(2), int64(2), object(5)
memory usage: 3.9+ MB

In [13]:
print("Contestants")

display(contestants.isnull().sum())

print()

print("Votes")

display(votes.isnull().sum())

Contestants

year                    0
to_country_id           0
to_country              0
performer               0
song                    2
place_contest         726
sf_num               1788
running_final        1027
running_sf           1788
place_final          1039
points_final         1040
place_sf             1788
points_sf            1788
points_tele_final    2244
points_jury_final    2244
points_tele_sf       2259
points_jury_sf       2259
composers               0
lyricists            1068
lyrics                  0
youtube_url             0
dtype: int64

Votes

year                   0
round                  0
from_country_id        0
to_country_id          0
from_country           0
to_country             0
total_points           0
tele_points        39613
jury_points        39613
dtype: int64

In [14]:
print("Contestants duplicates:",
      contestants.duplicated().sum())

print("Votes duplicates:",
      votes.duplicated().sum())

Contestants duplicates: 0
Votes duplicates: 0

In [15]:
print(
    contestants["year"].min(),
    contestants["year"].max()
)

print(
    votes["year"].min(),
    votes["year"].max()
)

1956 2026
1957 2026

In [16]:
contestants.groupby("year").size()

year
1956    13
1957    10
1958    10
1959    11
1960    13
        ..
2022    75
2023    68
2024    68
2025    68
2026    65
Length: 70, dtype: int64

In [17]:
contestants.to_csv(
    RAW_DATA / "contestants.csv",
    index=False
)

votes.to_csv(
    RAW_DATA / "votes.csv",
    index=False
)

print("Datasets copied into data/raw/")

Datasets copied into data/raw/